a = int(input("輸入系數 a : "))
b = int(input("輸入系數 b : "))
c = int(input("輸入系數 c : "))
d = (0 - b +(((b**2)-(4*a*c))**0.5))/(a*2)
e = (0 - b -(((b**2)-(4*a*c))**0.5))/(a*2)
print("方程式的根為 : " + "x1 = " + str(d) + ", " + "x2 = " + str(e))